import 'package:exchange_rate/models/Cryp_item.dart';
import 'package:exchange_rate/models/Rate_item.dart';

class CryptList{
  static List<CryptoItem> cryptoList =[
    CryptoItem(
        id: 1,
        name: "Doge Coin",
        names: "ด็อก คอยน์",
        rate: '8.81',
        image: 'doge.png',
        graph: 'dogg1.png',
        nickname: 'DOGE',
    ),
    CryptoItem(
      id: 2,
      name: "BitCoin",
      names: "บิทคอยน์",
      rate: '2,179,897.96',
      image: 'btc.png',
      graph: 'btcg1.png',
      nickname: 'BTC',
    ),
    CryptoItem(
      id: 3,
      name: "Ethereum",
      names: "อีเทอเรียม",
      rate: '159,560.36',
      image: 'eth.png',
      graph: 'ethg1.png',
      nickname: 'ETH',
    ),
    CryptoItem(
      id: 4,
      name: "Ripple",
      names: "ริปเพิล",
      rate: '40.64',
      image: 'xrp.png',
      graph: 'xrpg1.png',
      nickname: 'XRP',
    ),
    CryptoItem(
      id: 5,
      name: "Lite Coin",
      names: "ไลท์คอยด์",
      rate: '9,128.56',
      image: 'ltc.png',
      graph: 'ltcg1.png',
      nickname: 'LTC',
    ),
    CryptoItem(
      id: 6,
      name: "Tether",
      names: "เทเทอร์",
      rate: '33.42',
      image: 'ustd.png',
      graph: 'usdtg1.png',
      nickname: 'USDT',
    ),
    CryptoItem(
      id: 7,
      name: "Binance Coin",
      names: "ไบแนนซ์คอยน์",
      rate: '21,230',
      image: 'bnb.png',
      graph: 'bnbg1.png',
      nickname: 'BNB',
    ),
    CryptoItem(
      id: 8,
      name: "Stellar",
      names: "สเตเลอร์คอยน์",
      rate: '13.01',
      image: 'ste.png',
      graph: 'xlmg1.png',
      nickname: 'XLM',
    ),
    CryptoItem(
      id: 9,
      name: "Cardano",
      names: "คาดาโนคอยน์",
      rate: '69.71',
      image: 'ada.png',
      graph: 'adag1.png',
      nickname: 'ADA',
    ),
    CryptoItem(
      id: 10,
      name: "Wan Coin",
      names: "วานคอยน์",
      rate: '31.95',
      image: 'wan.png',
      graph: 'wang1.png',
      nickname: 'WAN',
    ),
  ];
}