import 'package:exchange_rate/models/Rate_item.dart';

class RateList {
  static List<RateItem> rateList = [
    RateItem(
        id: 1,
        name: "United State",
        names: "สหรัฐอเมริกา",
        rate: 32.87,
        image: 'usa1.png',
        nickname: 'USD'),
    RateItem(
        id: 2,
        name: "United Kingdom",
        names: "อังกฤษ",
        rate: 44.15,
        image: 'unk1.png',
        nickname: 'GBP'),
    RateItem(
        id: 3,
        name: "Barbados",
        names: "บาร์เบโดส",
        rate:  16.42,
        image: 'bba2.png',
        nickname: 'BBD'),
    RateItem(
        id: 4,
        name: "Austealia",
        names: "ออสเตรเลีย",
        rate: 24.04,
        image: 'atr1.png',
        nickname: 'EUR'),
    RateItem(
        id: 5,
        name: "Switzerland",
        names: "สวิตเซอร์แลนด์",
        rate: 35.79,
        image: 'sw1.png',
        nickname: 'CHF'),
    RateItem(
        id: 6,
        name: "New Zealand",
        names: "นิวซีแลนด์",
        rate: 23.16,
        image: 'new.png',
        nickname: 'NZD'),
    RateItem(
        id: 7,
        name: "Mexico",
        names: "เม็กซิโก",
        rate: 1.59,
        image: 'mexico1.png',
        nickname: 'MXN'),
    RateItem(
        id: 8,
        name: "Canada",
        names: "แคนนาดา",
        rate: 26.12,
        image: 'cnd1.png',
        nickname: 'CAD'),
    RateItem(
        id: 9,
        name: "European Union",
        names: "สหภาพยุโรป",
        rate:  37.65,
        image: 'erp1.png',
        nickname: 'EUR'),
    RateItem(
        id: 10,
        name: "Brazil",
        names: "บราซิล",
        rate:  6.03,
        image: 'brz1.png',
        nickname: 'BRL'),
    RateItem(
        id: 11,
        name: "NorWay",
        names: "นอร์เวย์",
        rate:  3.77,
        image: 'nor1.png',
        nickname: 'NOK'),
    RateItem(
        id: 12,
        name: "Peru",
        names: "เปรู",
        rate: 8.15,
        image: 'peru1.png',
        nickname: 'PEN'),
    RateItem(
        id: 13,
        name: "Brunei",
        names: "บรูไน",
        rate: 24.26,
        image: 'bun1.png',
        nickname: 'BND'),
    RateItem(
        id: 14,
        name: "Saudi Arabia",
        names: "ซาอุดิอาระเบีย",
        rate: 8.76,
        image: 'saud1.png',
        nickname: 'SAR'),
    RateItem(
        id: 15,
        name: "Jordan",
        names: "จอร์แดน",
        rate: 46.33,
        image: 'jor1.png',
        nickname: 'JOD'),
    RateItem(
        id: 16,
        name: "Sweden",
        names: "สวีเดน",
        rate: 3.77,
        image: 'swd1.png',
        nickname: 'SEK'),
    RateItem(
        id: 17,
        name: "United Arab Emirate",
        names: "สหรัฐอาหรับเอมิเรตส์",
        rate: 8.94,
        image: 'uae1.png',
        nickname: 'AED'),
    RateItem(
        id: 18,
        name: "Netherlands Antilles",
        names: "เนเธอร์แลนด์",
        rate:  18.34,
        image: 'ntl1.png',
        nickname: 'ANG'),
    RateItem(
        id: 19,
        name: "Romania",
        names: "โรมาเนีย",
        rate: 7.60,
        image: 'rmn1.png',
        nickname: 'RON'),
    RateItem(
        id: 20,
        name: "Turkey",
        names: "ตุรกี",
        rate: 3.31,
        image: 'tru1.png',
        nickname: 'TRY'),
  ];
}
